sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t examarchitect/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true examarchitect/docker-react npm run test --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env-1"
  bucker_name: "elasticbeanstalk-us-east-1-041450018416"
  bucker_path: "docker"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
